name: Marcus Sebastian P. Mc Nair
favicon: null
layout_spectrum: 0.70673
typography_spectrum: 0.23465
title: MM-MEDIA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f1f1f1'
    - '#afafaf'
    - '#8f8f8f'
    - '#1e1e1e'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
