name: MarcusMcnair
favicon: null
layout_spectrum: 0.24478
typography_spectrum: 0.23465
title: MMMedia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f1f1f1'
    - '#afafaf'
    - '#8f8f8f'
    - '#1e1e1e'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.8901838085148484
  rhythmicContrast: 0.75
purpose: []
